# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerId: ankii123
  imageName: 'newdevops:$(Build.BuildId)'


stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
    - script: |
       docker build -f Dockerfile -t $(dockerId)/$(imageName) .
       docker login -u $(dockerId) -p $(pswd)
       docker push $(dockerId)/$(imageName)
      displayName: 'Pushing Image'
      env:
        pswd: $(dockerPassword)
              